[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
backgroundColor = "#F4F6FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0D1B2A"
primaryColor = "#2B7BE9"
font = "sans serif"
