"""Widget registry — metadata for all available embeddable widgets."""

WIDGETS = [
    # ── Support ──────────────────────────────────────────────────────
    {
        "id": "support_metrics",
        "title": "Support Metrics",
        "domain": "support",
        "type": "metric",
        "default_height": 120,
        "data_source": "notion_sync.calls_weekly, notion_sync.sales_deals",
        "description": "KPI strip: weekly calls, answer rate, abandoned, pipeline deals.",
    },
    {
        "id": "support_call_volume",
        "title": "Call Volume",
        "domain": "support",
        "type": "chart",
        "default_height": 300,
        "data_source": "notion_sync.calls_weekly",
        "description": "Weekly call volume spline/area chart.",
    },
    {
        "id": "support_call_topics",
        "title": "Top Topics",
        "domain": "support",
        "type": "chart",
        "default_height": 300,
        "data_source": "notion_sync.calls_by_topic",
        "description": "Top 8 call topics by volume, horizontal bar.",
    },
    {
        "id": "support_agent_leaderboard",
        "title": "Agent Leaderboard",
        "domain": "support",
        "type": "chart",
        "default_height": 340,
        "data_source": "notion_sync.calls_by_agent",
        "description": "Top 10 agents ranked by call volume, horizontal bar.",
    },
    {
        "id": "support_answer_rate",
        "title": "Answer Rate",
        "domain": "support",
        "type": "chart",
        "default_height": 340,
        "data_source": "notion_sync.calls_weekly",
        "description": "Weekly answer rate trend with 80% target line.",
    },
    {
        "id": "support_call_mix",
        "title": "Call Mix",
        "domain": "support",
        "type": "chart",
        "default_height": 380,
        "data_source": "notion_sync.calls_log",
        "description": "Daily stacked bar: inbound answered, voicemail, outbound, Bland AI.",
    },

    # ── Finance ─────────────────────────────────────────────────────
    {
        "id": "finance_ar_buckets",
        "title": "AR Aging Buckets",
        "domain": "finance",
        "type": "chart",
        "default_height": 300,
        "data_source": "notion_sync.finance_ar_aging",
        "description": "AR amounts grouped by aging bucket with severity colors.",
    },
    {
        "id": "finance_ar_top_invoices",
        "title": "Overdue Invoices",
        "domain": "finance",
        "type": "feed",
        "default_height": 400,
        "data_source": "notion_sync.finance_ar_aging",
        "description": "Top 20 overdue invoices feed: client, invoice, amount, aging bucket.",
    },
    {
        "id": "finance_variance_heatmap",
        "title": "Variance Heatmap",
        "domain": "finance",
        "type": "chart",
        "default_height": 420,
        "data_source": "notion_sync.finance_variance",
        "description": "MoM % change by GL account x month, diverging colorscale.",
    },
    {
        "id": "finance_inbox_volume",
        "title": "Inbox Volume",
        "domain": "finance",
        "type": "chart",
        "default_height": 340,
        "data_source": "analytics.fact_emails",
        "description": "Weekly stacked bar: inbound, replied, outbound, internal (last 12 weeks).",
    },

    # ── Sales ───────────────────────────────────────────────────────
    {
        "id": "sales_metrics",
        "title": "Sales Metrics",
        "domain": "sales",
        "type": "metric",
        "default_height": 120,
        "data_source": "notion_sync.sales_deals",
        "description": "KPI strip: total deals, open deals, win rate, pipeline value.",
    },
    {
        "id": "sales_deal_funnel",
        "title": "Deal Funnel",
        "domain": "sales",
        "type": "chart",
        "default_height": 360,
        "data_source": "notion_sync.sales_deals",
        "description": "Deal value by stage funnel (Prospecting through Closed Won/Lost).",
    },
    {
        "id": "sales_rfp_by_source",
        "title": "RFPs by Source",
        "domain": "sales",
        "type": "chart",
        "default_height": 340,
        "data_source": "notion_sync.sales_rfp_pipeline",
        "description": "RFP count by source, stacked by relevance (HIGH/MEDIUM/LOW).",
    },
    {
        "id": "sales_rfp_timeline",
        "title": "RFP Timeline",
        "domain": "sales",
        "type": "chart",
        "default_height": 360,
        "data_source": "notion_sync.sales_rfp_pipeline",
        "description": "Due dates by source, bubble-sized by amount, colored by relevance.",
    },
    {
        "id": "sales_opp_heatmap",
        "title": "Opportunity Heatmap",
        "domain": "sales",
        "type": "chart",
        "default_height": 360,
        "data_source": "notion_sync.sales_opportunities",
        "description": "Source type vs urgency tier count matrix.",
    },
    {
        "id": "sales_state_map",
        "title": "State Channeler Map",
        "domain": "sales",
        "type": "chart",
        "default_height": 400,
        "data_source": "notion_sync.sales_state_profiles",
        "description": "Channeler model by US state choropleth map.",
    },
    {
        "id": "sales_state_fees",
        "title": "State Fees",
        "domain": "sales",
        "type": "chart",
        "default_height": 500,
        "data_source": "notion_sync.sales_state_profiles",
        "description": "Applicant cost by state, top-5 highlighted, horizontal bar.",
    },

    # ── Tickets ────────────────────────────────────────────────────────
    {
        "id": "tickets_metrics",
        "title": "Ticket Metrics",
        "domain": "tickets",
        "type": "metric",
        "default_height": 120,
        "data_source": "notion_sync.tickets_daily, notion_sync.tickets_open",
        "description": "KPI strip: opened (7d), closed (7d), net new, open backlog.",
    },
    {
        "id": "tickets_daily_trend",
        "title": "Daily Tickets",
        "domain": "tickets",
        "type": "chart",
        "default_height": 340,
        "data_source": "notion_sync.tickets_daily",
        "description": "Daily opened vs closed spline/area chart, weekdays, 90 days.",
    },

    # ── Revenue ────────────────────────────────────────────────────────
    {
        "id": "revenue_metrics",
        "title": "Revenue Metrics",
        "domain": "revenue",
        "type": "metric",
        "default_height": 120,
        "data_source": "notion_sync.revenue_decomposition",
        "description": "KPI strip: gross revenue, net revenue, net expansion, new customers.",
    },
    {
        "id": "revenue_gross_trend",
        "title": "Gross Revenue",
        "domain": "revenue",
        "type": "chart",
        "default_height": 340,
        "data_source": "notion_sync.revenue_decomposition",
        "description": "Monthly gross revenue stacked bar by business line with YoY annotations.",
    },
    {
        "id": "revenue_business_mix",
        "title": "Business Mix",
        "domain": "revenue",
        "type": "chart",
        "default_height": 340,
        "data_source": "notion_sync.revenue_decomposition",
        "description": "% of gross revenue by business line, stacked area chart.",
    },
    {
        "id": "revenue_nrr_grr",
        "title": "NRR / GRR",
        "domain": "revenue",
        "type": "metric",
        "default_height": 120,
        "data_source": "notion_sync.revenue_retention_summary",
        "description": "Net and gross revenue retention metric cards with MoM delta.",
    },
    {
        "id": "revenue_nrr_grr_trend",
        "title": "NRR & GRR Trend",
        "domain": "revenue",
        "type": "chart",
        "default_height": 300,
        "data_source": "notion_sync.revenue_retention_summary",
        "description": "NRR and GRR dual line chart with 100% reference line.",
    },
    {
        "id": "revenue_ttm_movement",
        "title": "TTM Movement",
        "domain": "revenue",
        "type": "chart",
        "default_height": 300,
        "data_source": "notion_sync.revenue_retention_summary",
        "description": "TTM revenue delta stacked bar by retention category (expansion/new/churn).",
    },
    {
        "id": "revenue_volume_metrics",
        "title": "Volume Metrics",
        "domain": "revenue",
        "type": "metric",
        "default_height": 120,
        "data_source": "notion_sync.unit_economics_monthly",
        "description": "KPI strip: total volume, platform fee/scan, relay fee/scan, ratio.",
    },
    {
        "id": "revenue_volume_pulse",
        "title": "Weekly Volume Pulse",
        "domain": "revenue",
        "type": "chart",
        "default_height": 340,
        "data_source": "notion_sync.volume_weekly",
        "description": "Weekly volume: platform vs relay overlaid bars with dual y-axis.",
    },
    {
        "id": "revenue_fee_decomp",
        "title": "Revenue per Scan",
        "domain": "revenue",
        "type": "chart",
        "default_height": 340,
        "data_source": "notion_sync.unit_economics_monthly",
        "description": "Fee decomposition (processing + gov + SAM) per scan, stacked area.",
    },
    {
        "id": "revenue_fee_trend",
        "title": "Processing Fee Trend",
        "domain": "revenue",
        "type": "chart",
        "default_height": 260,
        "data_source": "notion_sync.unit_economics_monthly",
        "description": "Platform vs relay processing fee per scan trend line.",
    },
    {
        "id": "revenue_conc_metrics",
        "title": "Concentration Metrics",
        "domain": "revenue",
        "type": "metric",
        "default_height": 120,
        "data_source": "notion_sync.customer_concentration_top",
        "description": "KPI strip: #1 customer, top-3/5/10 share of TTM revenue.",
    },
    {
        "id": "revenue_top_customers",
        "title": "Top 10 Customers",
        "domain": "revenue",
        "type": "chart",
        "default_height": 380,
        "data_source": "notion_sync.customer_concentration_top",
        "description": "Top 10 customers by TTM revenue, color-coded by segment.",
    },
    {
        "id": "revenue_conc_trend",
        "title": "Concentration Trend",
        "domain": "revenue",
        "type": "chart",
        "default_height": 380,
        "data_source": "notion_sync.customer_concentration_trend",
        "description": "Top-1/5/10/20 share of TTM revenue multi-line trend.",
    },
    {
        "id": "revenue_landscape",
        "title": "Revenue Landscape",
        "domain": "revenue",
        "type": "chart",
        "default_height": 400,
        "data_source": "notion_sync.customer_concentration_top",
        "description": "Top 20 customers treemap by TTM revenue, grouped by segment.",
    },

    # ── P&L ───────────────────────────────────────────────────────────
    {
        "id": "pnl_waterfall",
        "title": "P&L Waterfall",
        "domain": "pnl",
        "type": "chart",
        "default_height": 420,
        "data_source": "notion_sync.pnl_monthly",
        "description": "Latest month P&L bridge: revenue by BL → COGS deductions → gross profit.",
    },
    {
        "id": "pnl_margin_trend",
        "title": "Revenue & Margin Trend",
        "domain": "pnl",
        "type": "chart",
        "default_height": 400,
        "data_source": "notion_sync.pnl_monthly",
        "description": "Stacked revenue bars + COGS overlay + gross margin % line (dual axis).",
    },
    {
        "id": "pnl_sparklines",
        "title": "Business Line Cards",
        "domain": "pnl",
        "type": "metric",
        "default_height": 320,
        "data_source": "notion_sync.pnl_monthly",
        "description": "Small multiples: sparkline + revenue + MoM delta + margin per business line.",
    },
    {
        "id": "pnl_sankey",
        "title": "P&L Flow",
        "domain": "pnl",
        "type": "chart",
        "default_height": 440,
        "data_source": "notion_sync.pnl_monthly",
        "description": "Sankey: revenue flows from business lines → gross profit vs COGS split.",
    },
    {
        "id": "pnl_heatmap",
        "title": "Revenue Heatmap",
        "domain": "pnl",
        "type": "chart",
        "default_height": 360,
        "data_source": "notion_sync.pnl_monthly",
        "description": "Month x business line intensity grid with dollar values and margin %.",
    },
]
